# Generated by Django 4.2.27 on 2025-12-08 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_remove_noticia_contenido_remove_noticia_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='resumen',
        ),
        migrations.AddField(
            model_name='noticia',
            name='contenido',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
        migrations.RenameModel(
            old_name='PopupMessage',
            new_name='MensajePopUp',
        ),
        migrations.CreateModel(
            name='NoticiaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='contenido.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='MensajePopUpFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('mesajePU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotosPopUP', to='contenido.mensajepopup')),
            ],
        ),
    ]
