# Generated by Django 4.2.27 on 2025-12-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_remove_noticia_imagen_remove_noticia_resumen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(blank=True),
        ),
    ]
