# Generated by Django 4.2.27 on 2025-12-16 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_alter_noticia_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiafoto',
            name='uid',
        ),
        migrations.AlterField(
            model_name='noticiafoto',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
