# Generated by Django 4.2.27 on 2025-12-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_first_name_usuario_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_content_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
